services:
  news:
    container_name: news
    build: .
    ports:
      - "8000:8000"
    restart: always
    networks:
      - news-network
    working_dir: /usr/src/app

  tts:
    container_name: tts
    image: synesthesiam/opentts:en
    ports:
      - "5500:5500"
    networks:
      - news-network

  database:
    container_name: database
    image: ankane/pgvector:latest
    env_file: database/secrets.env
    environment:
      - POSTGRES_USER=daniel
      - POSTGRES_DB=news 
      - PGDATA=/var/lib/postgresql/data
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./SwarmDB/db_backup.sql:/usr/src/app/db_backup.sql
      # - ./SwarmDB/entrypoint.sh:/usr/src/app/entrypoint.sh
      # - ./SwarmDB/init_vector_db.sql:/docker-entrypoint-initdb.d/init_vector_db.sql  # Initialization scripts
      # - ./SwarmDB/init_embedding_tables.sql:/docker-entrypoint-initdb.d/init_embedding_tables.sql  # Initialization scripts
    expose:
      - "5432"
    ports:
      - "5432:5432"
    #entrypoint: ["bash", "/usr/src/app/entrypoint.sh"]
    stop_grace_period: 60s
    networks:
      - news-network

networks:
  news-network:
    name: news-network
    driver: bridge

volumes:
  pgdata: